# Generated by Django 5.0.9 on 2024-10-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=1)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
